// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Pstn struct {
	Number string `json:"number"`
	Dtmf   string `json:"dtmf"`
}

type Passphrase struct {
	Host *string `json:"host"`
	View string  `json:"view"`
}

type Session struct {
	Channel     string           `json:"channel"`
	Title       string           `json:"title"`
	IsHost      bool             `json:"isHost"`
	Secret      string           `json:"secret"`
	MainUser    *UserCredentials `json:"mainUser"`
	ScreenShare *UserCredentials `json:"screenShare"`
}

type ShareResponse struct {
	Passphrase *Passphrase `json:"passphrase"`
	Channel    string      `json:"channel"`
	Title      string      `json:"title"`
	Pstn       *Pstn       `json:"pstn"`
}

type UIDMuteState struct {
	UID  int  `json:"uid"`
	Mute bool `json:"mute"`
}

type User struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserCredentials struct {
	Rtc string  `json:"rtc"`
	Rtm *string `json:"rtm"`
	UID int     `json:"uid"`
}
