// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Passphrase struct {
	Host string `json:"host"`
	View string `json:"view"`
}

type PassphraseInput struct {
	Host string `json:"host"`
	View string `json:"view"`
}

type Password struct {
	Host string `json:"host"`
	View string `json:"view"`
}

type PasswordInput struct {
	Host string `json:"host"`
	View string `json:"view"`
}

type Session struct {
	Channel *string `json:"channel"`
	Rtc     string  `json:"rtc"`
	Rtm     string  `json:"rtm"`
	UID     int     `json:"uid"`
	IsHost  bool    `json:"isHost"`
}

type ShareResponse struct {
	Password   *Password   `json:"password"`
	Passphrase *Passphrase `json:"passphrase"`
}

type User struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
