// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Passphrase struct {
	Host string `json:"host"`
	View string `json:"view"`
}

type Password struct {
	Host string `json:"host"`
	View string `json:"view"`
}

type PasswordInput struct {
	Host string `json:"host"`
	View string `json:"view"`
}

type Session struct {
	Channel     *string          `json:"channel"`
	IsHost      bool             `json:"isHost"`
	MainUser    *UserCredentials `json:"mainUser"`
	ScreenShare *UserCredentials `json:"screenShare"`
}

type ShareResponse struct {
	Password   *Password   `json:"password"`
	Passphrase *Passphrase `json:"passphrase"`
	Pstn       *string     `json:"pstn"`
}

type User struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserCredentials struct {
	Rtc string  `json:"rtc"`
	Rtm *string `json:"rtm"`
	UID int     `json:"uid"`
}
